# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vreader < Formula
  desc "vreader"
  homepage "https://github.com/lll-lll-lll-lll/vreader"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.2/vreader_darwin_arm64.tar.gz"
      sha256 "eb5ef5ed3f38fc99e38fcdb88ac3552a5cc0eeb06a2ad97f7b3855a07ad12dc6"

      def install
        bin.install "vreader"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.2/vreader_darwin_x86_64.tar.gz"
      sha256 "6033d96a541f2986155e0b6f8ad68e178843698af76fa554c2074f6249c8e736"

      def install
        bin.install "vreader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.2/vreader_linux_x86_64.tar.gz"
      sha256 "c6ab4941502b871f358c58756bc686a622e90322a4a2bc4033e25a3d45144bfe"

      def install
        bin.install "vreader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.2/vreader_linux_arm64.tar.gz"
      sha256 "dcedc2123aa92e8ac84f503a073f5ca3ab9c0583c707195a7d0234a95ca48ab5"

      def install
        bin.install "vreader"
      end
    end
  end

  test do
    system "#{bin}/vreader --version"
  end
end
