# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vreader < Formula
  desc "vreader"
  homepage "https://github.com/lll-lll-lll-lll/vreader"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.3/vreader_darwin_x86_64.tar.gz"
      sha256 "7a34d234f70a6712b7974c0176aef197b07b012475fde635d70a6f4f05e67593"

      def install
        bin.install "vreader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.3/vreader_darwin_arm64.tar.gz"
      sha256 "c343235fda1d47e29ac5b00b7ebe8a53cc199842fc4e7573fca798f4f780ae92"

      def install
        bin.install "vreader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.3/vreader_linux_x86_64.tar.gz"
      sha256 "5ded98d45f1f7496f73623d50e6c382ae9c1785aadc145b821305970f4e0e48a"

      def install
        bin.install "vreader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lll-lll-lll-lll/webvtt-reader/releases/download/v0.1.3/vreader_linux_arm64.tar.gz"
      sha256 "c985ca4d20f4c48b0f0d0780a20cb953ac23ae88175bbd4b3570184a118e0018"

      def install
        bin.install "vreader"
      end
    end
  end

  test do
    system "#{bin}/vreader --version"
  end
end
